language: objective-c
xcode_project: UserDefaultsProperty.xcodeproj
xcode_scheme: UserDefaultsProperty-OSX
osx_image: xcode7.2
before_install: true
install: true
git:
  submodules: false
script:
  - brew install carthage
  - /usr/local/bin/carthage bootstrap --platform Mac
  - xctool -project UserDefaultsProperty.xcodeproj -scheme UserDefaultsProperty-OSX
  - xcodebuild test -project UserDefaultsProperty.xcodeproj -scheme UserDefaultsProperty-OSX